# Generated by Django 3.2.8 on 2021-10-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('follower', models.CharField(max_length=15)),
                ('following', models.CharField(max_length=15)),
            ],
        ),
    ]
