# Generated by Django 3.2.8 on 2021-10-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, default=[0], related_name='profile_followers', to='instagram.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, default=[0], related_name='profile_following', to='instagram.Profile'),
        ),
    ]
